server:
  port: 7778

spring:
  datasource:
    url: jdbc:h2:file:~/data/customer
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
    sql:
      init:
        mode: always
    h2:
      console:
        enabled: true