CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    NRB             VARCHAR(150)   NOT NULL,
    CURRENCY        VARCHAR(3)     NOT NULL,
    AVAILABLE_FUNDS DECIMAL(10, 2) NOT NULL,
    CUSTOMER_ID     BIGINT         NOT NULL
);