spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SebaaK/PRO_Microservices
          refresh-rate: 15
          timeout: 5
          search-paths: 'PRO_Microservices/,config-for-microservices/configuration/{application}/{profile}'
server:
  port: 8888